default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: "prajwal123"
  host: localhost

development:
  <<: *default
  database: blogging

test:
  <<: *default
  database: blogging_test

production:
  adapter: postgresql
  database: blogging_prod
  url: <%= ENV["DATABASE_URL"] %>

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
