default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  # password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  password: "prajwal123"
  host: localhost

development:
  <<: *default
  database: blogging

test:
  <<: *default
  database: blogging_test

production:
  <<: *default
  database: blogging_prod
